handler (superuser) for set role admin
PhySci/taxBot pull request #15
Opened 2022-06-12 12:48 UTC by Edw125

2022-06-12 17:49 UTC, PhySci commented on .gitignore
> +src/logs/
Need this folder. Please remove from .gitignore

2022-06-12 17:49 UTC, PhySci commented on src/app.py
> +from src.filters import IsAdmin
Please do not use src.* It breaks import logic

2022-06-12 17:49 UTC, PhySci commented on src/db.py
> +            _logger.info(f"Role of user with email '{email}' has been changed to 'admin'. STATUS_OK")
Please use :s instead of f-string. What's the purpose of "STATUS_OK"? I think it's redundant.

2022-06-12 17:49 UTC, PhySci commented on src/db.py
> +                f"User with e-mail '{email}' does not exists in database. STATUS_FAIL"
Not f-string please

2022-06-12 17:49 UTC, PhySci commented on src/db.py
> +                f"Role of user with e-mail '{email}' is already 'admin'. STATUS_PERMISSIONS_EXIST"
Not f-string please

2022-06-12 17:49 UTC, PhySci commented on src/handlers.py
> +from src.settings import SUPERUSER_IDS
Do not use _src_ . It breaks import logic

2022-06-12 17:49 UTC, PhySci commented on src/handlers.py
> +        await message.answer('Вы не являетесь администратором')
Need _return_ after `await message.answer`?

2022-06-12 17:49 UTC, PhySci commented on src/mailing.py
> +    file_pth = os.path.join(os.path.dirname(__file__), "tmp", datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".xlsx")
White space is not recommended in functions' arguments.
https://peps.python.org/pep-0008/#other-recommendations

2022-06-12 17:49 UTC, PhySci commented on src/mailing.py
> -        worksheet.write(row+1, 0, el["FIO"])
The same here. https://peps.python.org/pep-0008/#other-recommendations

2022-06-13 10:14 UTC, PhySci requested changes
Переделай пожалуйста все импорты, начинаютщиеся с **src**

2022-06-13 10:14 UTC, PhySci commented on src/filters.py
> +from src.settings import SUPERUSER_IDS
Если ты импортируешь что-то вот так
`from **src**.settings import XXX`
то это работает у тебя локально, но не работает в докере. Необходимо использовать относительный путь, т.е.
`from settings import XXX`

2022-06-13 10:14 UTC, PhySci commented on src/handlers.py
> +from src.settings import SUPERUSER_IDS
The problem does not resolved

2022-06-13 18:13 UTC, Edw125 commented
Resolved in feature/superuser

2022-06-13 18:13 UTC, closed without merging